# name: C/C++ CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: configure
#       run: ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck


# .github/workflows/cpp-ci.yml
name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Download Catch2
      run: |
        wget https://github.com/catchorg/Catch2/releases/download/v2.13.7/catch.hpp
        mv catch.hpp .

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      working-directory: build
      run: ./tests
