name: C++ Build and Test Workflow
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make
      
      - name: Download Catch2
        run: wget https://github.com/catchorg/Catch2/releases/download/v2.13.7/catch.hpp
      
      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
      
      - name: Run tests
        run: |
          cd build
          ./tests
      
      - name: Run main calculator program
        run: |
          cd build
          ./calculator